#!/usr/bin/env bash
if [[ ! -d $PWD/venv ]]; then
    python3 -m virtualenv $PWD/venv
    source $PWD/venv/bin/activate
    pip install -r $PWD/requirements.txt
    deactivate
fi

source $PWD/venv/bin/activate
./main.py
deactivate
